name: "Flutter"
description: "Action to install Flutter"
inputs:
  FLUTTER_VERSION:
    description: "Flutter version"
    default: "3.10.5"
  keystore-path:
    description: "Path to Java keystore"
    default: "/etc/pki/java/cacerts"
runs:
  using: "composite"
  steps:
    - name: Install Flutter
      shell: bash
      run: |
        export FLUTTER_VERSION="${{ inputs.FLUTTER_VERSION }}"

        FLUTTER_RUNNER_TOOL_CACHE=${RUNNER_TOOL_CACHE}/${FLUTTER_VERSION}

        if [ ! -d "${FLUTTER_RUNNER_TOOL_CACHE}" ]; then

        	echo "Installing Flutter SDK"

          echo "Installing XZ - LZMA compression utilities"
          
        	echo "Downloading release file"

          wget -P /tmp -q --show-progress --progress=bar:force:noscroll https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_${FLUTTER_VERSION}-stable.tar.xz

          mkdir -p "${FLUTTER_RUNNER_TOOL_CACHE}"

          echo "Extracting compressed downloaded file"

          tar -C "${FLUTTER_RUNNER_TOOL_CACHE}" -xf /tmp/flutter_linux_${FLUTTER_VERSION}-stable.tar.xz > /dev/null

          if [ $? -ne 0 ]; then
              echo -e "::error::Flutter SDK download failed."

              rm -Rf "${FLUTTER_RUNNER_TOOL_CACHE}"
              exit 1
          fi

        else
        	echo "Flutter SDK found in cache. The cached SDK is going to be used."
        fi

    - name: Configure pub to use a fixed location.
      shell: bash
      run: |
        echo "PUB_CACHE=${FLUTTER_RUNNER_TOOL_CACHE}/.pub-cache" >> $GITHUB_ENV

    - name: Update paths.
      shell: bash
      run: |
        echo "${FLUTTER_RUNNER_TOOL_CACHE}/.pub-cache/bin" >> $GITHUB_PATH
        echo "${FLUTTER_RUNNER_TOOL_CACHE}/flutter/bin" >> $GITHUB_PATH

    - name: Set the tag
      shell: bash
      run: |
        if [ -z "${{inputs.tag}}" ] then
            echo "final_tag=latest" >> $GITHUB_ENV
          else
            echo "final_tag=${{inputs.tag}}" >> $GITHUB_ENV
        fi
